services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo:/data
    ports:
      - 28017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
<<<<<<< HEAD
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: false
=======
      ME_CONFIG_MONGODB_URL: mongo://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "true"
<<<<<<< HEAD
>>>>>>> 21a881c (backend schaice)
=======
>>>>>>> 21a881c (backend schaice)
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongodb

volumes:
  mongo: